/* -*-  Mode: C++; c-file-style: "gnu"; indent-tabs-mode:nil; -*- */
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Natalya Rozhnova <natalya.rozhnova@lip6.fr>
 */

/**
 * question ????
 * @brief this is a single conversation scenario, calculate the queue size of interest and data
 *
 * 1.Define a function: CheckQueueSize (Ptr<Queue> queue, Ptr<NetDeviceFace> ndf)
 * 2.Define a function: CheckInterestQueueSize (Ptr<NetDeviceFace> ndf)
 * 3.Read topology
 * 4.Getting containers for the consumer/producer
 * 5.Install CCNx stack on node router
 * 6.Installing NDN-drop-tail-queue to manage the data queue on each router.
 * 7.Install CCNx stack on nodes client or server
 * 8.Installing global routing interface on all nodes
 * 9.Install consumers
 * 10.Register prefix with global routing controller and install producer
 * 11.Install servers
 * 12.calculate and install FIBs
 * 13.Check data chunk queue size
 * 14.Check Interest queue size
 *
 * For different steps, search with "X.(X from 1 to 11)"
 */

#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/ndnSIM-module.h"
#include "ns3/ndn-hobhis-net-device-face.h"

#include "ns3/point-to-point-net-device.h"
#include "ns3/point-to-point-module.h"

#include "ns3/ndn-drop-tail-queue.h"

using namespace ns3;
using namespace ndn;

std::stringstream filePlotQueue;
std::stringstream filePlotInterestQueue;

/**
 * @brief check the queue size of data chunk
 * @param queue of data chunk
 * @param ndf net device face
 */

//1.
void
CheckQueueSize (Ptr<Queue> queue, Ptr<NetDeviceFace> ndf)
{
	uint32_t DqtotalSize;
	// the initialization length of the consumer's queue is 0
	uint32_t queuec1 = 0;

	// if HobhisEnable is true
	if(ndf->HobhisEnabled()==true)
	{
		// cast from base class (Queue) to child class( NDNDropTailQueue)
		// static so the variable associate the base class didn't have the methods of children class
		Ptr<NDNDropTailQueue> ndnqueue = StaticCast<NDNDropTailQueue> (queue);
		if(ndnqueue != NULL)
		{
			// if ndnqueue is not empty,we obtain the queue size of each flow
			queuec1 = ndnqueue->GetQueueSizePerFlow("/c1");
			// we obtain the total size of data chunk queue
			DqtotalSize = ndnqueue->GetDataQueueLength();
		}
	}
	// if hobhis is not active,the data chunk queue size is the pakets's number
	else DqtotalSize = queue->GetNPackets();

 // check queue size every 1/100 of a second
  Simulator::Schedule (Seconds (0.01), &CheckQueueSize, queue, ndf);
 // print the data chunk queue size  in the current time
  std::ofstream fPlotQueue (filePlotQueue.str ().c_str (), std::ios::out|std::ios::app);
  fPlotQueue << Simulator::Now ().GetSeconds ()
		     << " @ "<< queue
		     <<" /c1 "<<queuec1
		     <<" -total " <<DqtotalSize
		     << std::endl;
  fPlotQueue.close ();
}

//2.
void
CheckInterestQueueSize (Ptr<NetDeviceFace> ndf)
{
	// cast from base class (NetDeviceFace) to child class(HobhisNetDeviceFace)
	// static so the variable associate the base class didn't have the methods of children class
	Ptr<HobhisNetDeviceFace> hndf = StaticCast<HobhisNetDeviceFace> (ndf);

	// define variable IqSize as Interest queue size
	uint32_t IqSize = hndf->GetQueueLength();

	// check queue size every 1/100 of a second
	Simulator::Schedule (Seconds (0.01), &CheckInterestQueueSize, ndf);

	// print the Interest queue size in the current time
	std::ofstream fPlotQueue (filePlotInterestQueue.str ().c_str (), std::ios::out|std::ios::app);
	fPlotQueue << Simulator::Now ().GetSeconds ()
			   << " @ "<< hndf
			   << " -ql " <<IqSize
			   << std::endl;
	fPlotQueue.close ();
}

int
main (int argc, char *argv[])
{
  // default writeForplot is false
  bool writeForPlot = false;
  // default there is no delay for the data packet
  std::string RSmin("0"), RSmax("0");

  // add  different variables as the parameters
  // ****<command-line.h>(ns3)
  CommandLine cmd;
  cmd.AddValue ("wfp", "<0/1> to write results for plot (gnuplot)", writeForPlot); // if you want to obtain the tracing files
  cmd.AddValue("RSmin", "minimum delay generated by server for each data packet, [seconds]", RSmin);
  cmd.AddValue("RSmax", "maximum delay generated by server for each data packet, [seconds]", RSmax);
  // analyze the command parameters as CommandLine
  cmd.Parse (argc, argv);

  //3.
  // Read topology
  // ****<annotated-topology-reader.h>(ndnsim)
  AnnotatedTopologyReader topologyReader ("", 25);
  topologyReader.SetFileName ("src/ndnSIM/examples/topologies/hobhis-baseline.txt");
  topologyReader.Read ();

  //4.
  // Getting containers for the consumer/producer
  Ptr<Node> c1 = Names::Find<Node> ("C1");
  Ptr<Node> r1 = Names::Find<Node> ("R1");
  Ptr<Node> s1 = Names::Find<Node> ("P1");

  //5.
  // Install CCNx stack on all nodes
  ndn::StackHelper ndnHelper;
  // Set forwarding strategy best route
  ndnHelper.SetForwardingStrategy ("ns3::ndn::fw::BestRoute");

  /* enable shaper
   * client/server (is the node a client or server? This parameter should be enabled on router nodes only)
   * INTEREST buffer size
   * target
   * convergence speed (design parameter)
   * dynamic adjustment of design parameter (only for monoflow))
   */
  // shaper enable,client/server,buffer size(max interest)=10000,queue target=60,convergence speed=0.7( h in the paper????)
  ndnHelper.EnableHobhis (true, false, 10000, 60, 0.7);
  // contentstore strategy: Lru, size maximum=1
  ndnHelper.SetContentStore ("ns3::ndn::cs::Lru", "MaxSize", "1"); // almost no caching
  // install for routeur1
  ndnHelper.Install (r1);

//6.
//**************************** Installing NDN-drop-tail-queue to manage the data queue on each router. ******************************************

  // Router 1 interface 0
  // ****<object-factory.h>(ns3)
  ObjectFactory factory;
  // define variable type L3Protocol ndn from r1
  // ****<ndn-l3-protocol.h>(ndnsim)
  Ptr<L3Protocol> ndn = r1->GetObject<L3Protocol> ();
  // define variable type Face face from ndn
  Ptr<Face> face = ndn->GetFace (0);
  // cast from base class (Face) to child class( NetDeviceFace)
  // dynamic so the variables associate the base class  have the methods of children class
  Ptr<NetDeviceFace> ndf = DynamicCast<NetDeviceFace>(face);
  // define variable type NetDevice nd from ndf
  // ****<net-device.h>(ns3)
  Ptr<NetDevice> nd = ndf->GetNetDevice();
  // cast from base class(NetDevice)to child class(PointToPointNetDevice)
  // static so the variable associate the base class didn't have the methods of children class
  Ptr<PointToPointNetDevice> p2pnd = StaticCast<PointToPointNetDevice> (nd);

  // define type ID called ns3::NDNDropTailQueue
  factory.SetTypeId("ns3::NDNDropTailQueue");
  //default maxpacket=100
  Config::SetDefault ("ns3::NDNDropTailQueue::MaxPackets", UintegerValue (100));
  // create a queueA
  Ptr<Queue> queueA = factory.Create<Queue> ();
  // cast from base class (Queue) to child class( NDNDropTailQueue)
  // static so the variable associate the base class didn't have the methods of children class
  Ptr<NDNDropTailQueue> ndnqueue = StaticCast<NDNDropTailQueue> (queueA);
  // set ndnqueue mode
  ndnqueue->SetMode(ndn::NDNDropTailQueue::QUEUE_MODE_PACKETS);
  // connect p2p face with queueA
  p2pnd->SetQueue (queueA);

  //***********************************************************************************************************************************************************

  //7.
  // Install CCNx stack on all nodes
  ndn::StackHelper ndnHelper1;
  // Set forwarding strategy best route
  ndnHelper1.SetForwardingStrategy ("ns3::ndn::fw::BestRoute");
  //enable shaper, client or server
  ndnHelper1.EnableHobhis (true, true);
  // contentstore strategy: Lru, size maximum=1
  ndnHelper1.SetContentStore ("ns3::ndn::cs::Lru", "MaxSize", "1"); // almost no caching
  // install client1
  ndnHelper1.Install (c1);
  // install server1
  ndnHelper1.Install (s1);

  //8.
  // Installing global routing interface on all nodes
  // ****<ndn-global-routing-helper.h>(ndnsim)
   ndn::GlobalRoutingHelper ndnGlobalRoutingHelper;
   ndnGlobalRoutingHelper.InstallAll ();

  //9.
  // Install consumers
  // ****<ndn-app-helper.h>(ndnsim) define consumerHelper as  type rate CBR
  ndn::AppHelper consumerHelper ("ns3::ndn::ConsumerCbr");
  // set consumer frequency=10000 chunk/second
  consumerHelper.SetAttribute("Frequency", StringValue ("10000.0"));
  // set interest prefix "/c1"
  consumerHelper.SetPrefix ("/c1");
  // install for c1
  consumerHelper.Install (c1);

  //10.
  // Register prefix with global routing controller and install producer

  ndnGlobalRoutingHelper.AddOrigins ("/c1", s1);

  //11.
  // Install servers
  ndn::AppHelper producerHelper ("ns3::ndn::Producer");
  //the capacity of producter=1000
  producerHelper.SetAttribute ("PayloadSize", StringValue("1000"));
  producerHelper.SetAttribute ("RandomDelayMin", StringValue(RSmin));
  producerHelper.SetAttribute ("RandomDelayMax", StringValue(RSmax));
  // set interest prefix "/c1"
  producerHelper.SetPrefix ("/c1");
  // install for s1
  producerHelper.Install (s1);

  //12.
  // Calculate and install FIBs
  ndnGlobalRoutingHelper.CalculateRoutes ();

  // Stop Simulator at 50s
  Simulator::Stop (Seconds (50.0));

  // Queue trace

  std::string pathOut = ".";
  // if flag writeForPlot is true
  if (writeForPlot)
  	  {
	  	  //13.
	  	  // Check data chunk queue size

	  	  filePlotQueue << pathOut << "/" << "data-queue-r1-c1.plotme";
	  	  remove (filePlotQueue.str ().c_str ());

	  	  // define variable type L3Protocol ndn from r1
	  	  Ptr<L3Protocol> ndn = r1->GetObject<L3Protocol> ();
	  	  // define variable type Face face from ndn
	  	  Ptr<Face> face = ndn->GetFace (0);
	  	  // cast from base class (Face) to child class( NetDeviceFace)
	  	  // dynamic so the variables associate the base class  have the methods of children class
	  	  Ptr<NetDeviceFace> ndf = DynamicCast<NetDeviceFace>(face);
	  	  // define type NetDevie nd
	  	  Ptr<NetDevice> nd = ndf->GetNetDevice();
	  	  // cast from base class(NetDevice)to child class(PointToPointNetDevice)
	  	  // static so the variable associate the base class didn't have the methods of children class
	  	  Ptr<PointToPointNetDevice> p2pnd = StaticCast<PointToPointNetDevice> (nd);
	  	  // get queue from PointToPointNetDevice p2pnd
	  	  Ptr<Queue> queue = p2pnd->GetQueue();

	  	  Simulator::ScheduleNow (&CheckQueueSize, queue, ndf);

	  	  //14.
	  	  // Check Interest queue size
	  	  Ptr<Face> face1 = ndn->GetFace (1);
	  	  // cast from base class (Face) to child class( NetDeviceFace)
	      // dynamic so the variables associate the base class  have the methods of children class
	  	  Ptr<NetDeviceFace> ndf1 = DynamicCast<NetDeviceFace>(face1);
	  	  filePlotInterestQueue << pathOut << "/" << "interest-queue-r1-s1.plotme";
	  	  remove (filePlotInterestQueue.str ().c_str ());
	  	  Simulator::ScheduleNow (&CheckInterestQueueSize, ndf1);
  	  }
  // Run simulator
  Simulator::Run ();
  // Destroy simulator
  Simulator::Destroy ();

  return 0;
}
